apiVersion: v1
kind: Secret
metadata:
  name: kube-apiserver
type: Opaque
data:
  apiserver.key: {{ required "serverKey can't be empty!" .Values.serverKey | b64enc }}
  apiserver.crt: {{ required "serverCertificate can't be empty!" .Values.serverCertificate | b64enc }}
  service-account.key: {{ required "serviceAccountPrivateKey can't be empty!" .Values.serviceAccountPrivateKey | b64enc }}
  ca.crt: {{ required "caCertificate can't be empty!" .Values.caCertificate | b64enc }}
  front-proxy-client.crt: {{ required "frontProxyClientCertificate can't be empty!" .Values.frontProxyClientCertificate | b64enc }}
  front-proxy-client.key: {{ required "frontProxyClientKey can't be empty!" .Values.frontProxyClientKey | b64enc }}
  front-proxy-ca.crt: {{ required "frontProxyCACertificate can't be empty!" .Values.frontProxyCACertificate | b64enc }}
  apiserver-kubelet-client.crt: {{ required "kubeletClientCertificate can't be empty!" .Values.kubeletClientCertificate | b64enc }}
  apiserver-kubelet-client.key: {{ required "kubeletClientKey can't be empty!" .Values.kubeletClientKey | b64enc }}
  etcd-ca.crt: {{ required "etcdCACertificate can't be empty!" .Values.etcdCACertificate | b64enc }}
  apiserver-etcd-client.crt: {{ required "etcdClientCertificate can't be empty!" .Values.etcdClientCertificate | b64enc }}
  apiserver-etcd-client.key: {{ required "etcdClientKey can't be empty!" .Values.etcdClientKey | b64enc }}
