apiVersion: v1
kind: Secret
metadata:
  name: kube-apiserver
type: Opaque
data:
  apiserver.key: {{ required "serverKey can't be empty!" .Values.serverKey | b64enc }}
  apiserver.crt: {{ required "serverCertificate can't be empty!" .Values.serverCertificate | b64enc }}
  service-account.crt: {{ required "serviceAccountPublicKey can't be empty!" .Values.serviceAccountPublicKey | b64enc }}
  ca.crt: {{ required "caCertificate can't be empty!" .Values.caCertificate | b64enc }}
