apiVersion: v1
kind: Secret
metadata:
  name: kube-apiserver
type: Opaque
data:
  apiserver.key: {{ required "kubernetesAPIServerKey can't be empty!" .Values.kubernetesAPIServerKey | b64enc }}
  apiserver.crt: {{ required "kubernetesAPIServerCertificate can't be empty!" .Values.kubernetesAPIServerCertificate | b64enc }}
  service-account.crt: {{ required "serviceAccountPublicKey can't be empty!" .Values.serviceAccountPublicKey | b64enc }}
  ca.crt: {{ required "kubernetesCACertificate can't be empty!" .Values.kubernetesCACertificate | b64enc }}
